-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "postedDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "readTime" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "smallTitle" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "writerName" TEXT NOT NULL DEFAULT 'Admin';
